### ISSUE TITLE
Winkel der Pixel rechts des Viewpoints

### ISSUE THREAD

**Issue by moritzbeck** [chrih/Projekt_Algo_GIS#5]
Die Winkelberechnung für die Pixel rechts des Viewpoints dürfte falsch sein.
@jonakalkus Wo stand, dass `Math.atan2` den Winkel _im_ Uhrzeigersinn angibt? Kann grad nur _gegen_ den Uhrzeigersinn finden (was ja auch die mathematische Konvention ist).

Muss Zeile 43 [1] nicht eigentlich `Math.atan2(dy - 0.5, dx - 0.5);` heißen?!
Wegen `dy == 0` können wir sogar gleich `Math.atan2(-0.5, dx - 0.5);` schreiben.
(ebenso in Zeile 48 [2])

[1] https://github.com/chrih/Projekt_Algo_GIS/blob/52c5509954a2325e9d564abdcc42997b31854700/src/de/uniwue/algogis/viewshed/sweep/SweepEvent.java#L43
[2] https://github.com/chrih/Projekt_Algo_GIS/blob/52c5509954a2325e9d564abdcc42997b31854700/src/de/uniwue/algogis/viewshed/sweep/SweepEvent.java#L48

![schaubild winkel](https://cloud.githubusercontent.com/assets/12851935/8580135/26bba846-25b9-11e5-862a-24dd67c11b6c.png)

**Comment by jonakalkus** [comment]
Das hatte ich irgendwo von stackoverflow, find's grade nicht mehr. So wie ich's dann im Code schnell ausprobiert hatte, schien es auch innerhalb der SweepEvent zu passen. (Sofern man von ausgeht, dass es clockwise den Winkel angibt) 
Hab ich wohl was verdreht.. Danke für den Hinweis. Oder habe ich bei der Berechnung von dx/dy was verdreht und deswegen falsche Winkel als "richtig" interpretiert..!? Mal sehen, ich schau's mir gleich nochmal genauer an.

**Comment by moritzbeck** [comment]
Die [Dokumentation](https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#atan2-double-double-) für `Math.atan2` deckt sich zumindest damit, dass sich die Winkel gegen den Uhrzeigersinn erhöhen.
