### ISSUE TITLE
Reihenfolge Bearbeitung der Events

### ISSUE THREAD

**Issue by moritzbeck** [chrih/Projekt_Algo_GIS#6]
Die Reihenfolge, in der die Events abgearbeitet werden, ist nicht spezifiziert. Das kann dazu führen, dass sie in einer falschen Reihenfolge abgearbeitet werden.
Das liegt daran, dass die `for (SweepEvent s : eventList)` Schleife den Iterator der `PriorityQueue` benutzt, für diesen steht in der Dokumentation [1]:

> The iterator does not return the elements in any particular order.

Vermutlich wäre es am besten, die Elemente einfach zu `poll()`-en.

[1] https://docs.oracle.com/javase/8/docs/api/java/util/PriorityQueue.html#iterator--

**Comment by jonakalkus** [comment]
Danke! Hab's geändert, darauf wäre ich nicht so schnell gekommen.
